### ISSUE TITLE
Documentation missing?

### ISSUE THREAD

**Issue by Turbo87** [ember-codemods/ember-codemods-telemetry-helpers#11]
What is this project and how can it be used? The README doesn't seem to have a lot of information currently... 😅

**Comment by scottkidder** [comment]
It appears it was extracted from (ember-native-class-codemod)(https://github.com/ember-codemods/ember-native-class-codemod). That codemod uses puppeteer (via this lib) to visit the Ember app and gather `telemetry` necessary to convert to native classes. Definitely a cool concept that could open up a lot :thinking:
