### ISSUE TITLE
Pull the work from a no-implicit-this PR to here

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-codemods/ember-codemods-telemetry-helpers#2]
Courtesy of @patocallaghan
https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/9
https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/10

**Comment by patocallaghan** [comment]
Both of these are done now 🎉 You can close this issue.

**Comment by NullVoxPopuli** [comment]
woo!
