### ISSUE TITLE
Support passing puppeteer arguments

### ISSUE THREAD

**Issue by chriskrycho** [ember-codemods/ember-codemods-telemetry-helpers#8]
For debugging purposes, it's useful to be able to pass Puppeteer arguments during invocation. For example, on debugging the ember-native-class-codemod, I ended up needing to `volta install` the codemod and then manually modify the Puppeteer arguments in the installation location on disk to launch it in non-headless mode in order to understand the problem we were seeing.

**Proposal:** All exported functions which result in a Puppeteer launch should take as their second argument a hash of Puppeteer options, and this can be documented in their public APIs in the README.

**Comment by scottkidder** [comment]
I had to do a similar thing in order to pass `--no-sandbox` to puppeteer to get ember-native-class-codemod working on Debian bullseye.
